# Generated by Django 5.2.6 on 2025-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='depth',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coord',
            name='latitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coord',
            name='longitude',
            field=models.FloatField(max_length=200),
        ),
    ]
